Added localization of the podsec-k8s-rbac package.

diff --git a/podsec-k8s-rbac/bin/podsec-k8s-rbac-bindrole b/podsec-k8s-rbac/bin/podsec-k8s-rbac-bindrole
--- a/podsec-k8s-rbac/bin/podsec-k8s-rbac-bindrole
+++ b/podsec-k8s-rbac/bin/podsec-k8s-rbac-bindrole
@@ -1,11 +1,13 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec-k8s-rbac'
 
 cmdname=$(basename $0)
 . podsec-k8s-rbac-functions
 
 if [ $# -lt 4 -o $# -gt 5 ]
 then
-  echo -ne "Формат:\n$0 имя_пользователя role|clusterrole|role=clusterrole роль имя_связки_роли [namespace]"
+  echo -ne "$(gettext 'Format':)\n$cmdname $(gettext 'username') role|clusterrole|role=clusterrole $(gettext 'role') $(gettext 'role_bundle_name') [namespace]" >&2
   exit 1
 fi
 
@@ -28,7 +30,7 @@ fi
 
 if [ -z "$isSystem" -a ! -d /home/$user  ]
 then
-  echo "Пользователь $user не существует"
+  echo -ne "$(gettext 'User') $user $(gettext 'does not exist')" >&2
   exit 1
 fi
 
@@ -39,20 +41,21 @@ case $bindedRoleType in
     roleType="role"
     bindedRoleType='clusterrole'
     break;;
-  *) echo "Неверный тип кластерной роли $bindedRoleType";
-    echo -ne "Формат:\n$0 имя_пользователя role|clusterrole|role=clusterrole роль имя_связки_роли [namespace]";
+  *)
+    echo "$(gettext 'Invalid cluster role type') $bindedRoleType" >&2
+    echo -ne "$(gettext 'Format':)\n$cmdname $(gettext 'username') role|clusterrole|role=clusterrole $(gettext 'role') $(gettext 'role_bundle_name') [namespace]" >&2
     exit 1
 esac
 
 if [ -n "$namespace" -a "$roleType" == 'clusterrole' ]
 then
-  echo "namespace неприменимо к кластерной роли"
+  echo "$(gettext 'namespace is not applicable to cluster role')" >&2
   exit 1
 fi
 
 if [ -z "$namespace" -a  "$roleType" == 'role' ]
 then
-  echo "При привязке обычной роли необходимо указать namespace"
+   echo "$(gettext 'When binding a regular role, you must specify a namespace')"  >&2
   exit 1
 fi
 
@@ -60,11 +63,11 @@ if ! kubectl $namespace get ${bindedRoleType} $roleName >/dev/null 2>&1
 then
   if [ "$roleType" == 'clusterrole' ]
   then
-    roleTxt="Кластерная роль"
+    roleTxt="$(gettext 'Cluster role')"
   else
-    roleTxt="Роль"
+    roleTxt="$(gettext 'Role')"
   fi
-  echo "$roleTxt '$roleName' отсутствует"
+  echo "$roleTxt '$roleName' $(gettext 'absent')" >&2
   exit 1
 fi
 
diff --git a/podsec-k8s-rbac/bin/podsec-k8s-rbac-create-kubeconfig b/podsec-k8s-rbac/bin/podsec-k8s-rbac-create-kubeconfig
--- a/podsec-k8s-rbac/bin/podsec-k8s-rbac-create-kubeconfig
+++ b/podsec-k8s-rbac/bin/podsec-k8s-rbac-create-kubeconfig
@@ -1,11 +1,14 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec-k8s-rbac'
 
+export PROGRAMM=$0
 . podsec-k8s-rbac-functions
 
 cmdname=$(basename $0)
 if [ $# -lt 1 ]
 then
-  echo "Формат вызова: $0 <пользователь>[@<удаленный_пользователь>] [<группа1> ...]"
+  echo "$(gettext 'Format'):\n $PROGRAMM $(gettext 'user')[@<(gettext 'remote_user')>] [<(gettext 'group')1> ...]" >&2
   exit 1
 fi
 user=$1
@@ -38,41 +41,42 @@ clusterName=$(getClusterName)
 
 if [ ! -d $KUBECONFIGDIR ]
 then
-  echo "$KUBECONFIG каталог $KUBECONFIGDIR отсутствует" >&1
+  echo "$KUBECONFIG $(gettext 'directory') $KUBECONFIGDIR $(gettext 'absent')" >&2
   exit 1
 fi
 
 if ! cd $KUBECONFIGDIR
 then
-  echo "Нет прав на доступ в каталог $KUBECONFIGDIR"
+  echo "$(gettext 'No rights to access the directory') $KUBECONFIGDIR" >&2
   exit 1
 fi
 
 # Создание личного (private) ключа
-echo -ne "Создание личного (private) ключа..."
+echo "$(gettext 'Creating a personal') (private) $(gettext 'key')" >&2
 openssl genrsa -out $user.key 2048 >/dev/null 2>&1
 if [ ! -s "$user.key" ]
 then
-  echo "Файл личного ключа '$user.key' не создан"
+  echo "$(gettext 'Private key file') '$user.key' $(gettext 'not created')" >&2
   exit 1
 fi
-echo "личный (private) ключ создан"
+echo "$(gettext 'Private key file') '$user.key' $(gettext 'created')" >&2
 
 # Создание запроса на подпись сертификата (CSR)
-echo -ne "Создание запроса на подпись сертификата (CSR)..."
+echo -ne "$(gettext 'Creating a Certificate Signing Request') (CSR)..." >&2
 openssl req -new -key $user.key -out $user.csr -subj "/CN=$user$groups"
 if [ ! -s "$user.csr" ]
 then
-  echo "Файл запроса на подпись сертификата '$user.key' не создан"
+  echo "$(gettext 'Certificate Signing Request file') 'csr' $(gettext 'not created')" >&2
   exit 1
 fi
-echo "запрос на подпись сертификата создан"
+echo "$(gettext 'Certificate Signing Request file') 'csr' $(gettext 'created')" >&2
 
 # Удалить предыдущий запрос если есть
-kubectl delete certificatesigningrequest.certificates.k8s.io $user >/dev/null 2>&1
+kubectl delete certificatesigningrequest.certificates.k8s.io $user >/dev/null
 request=$(base64 < $user.csr | tr -d "\n")
+
 # Запись CSR в кластер
-echo -ne "Запись запроса на подпись сертификата CSR в кластер..."
+echo -ne "$(gettext 'Writing CSR certificate signing request to cluster')..." >&2
 cat <<EOF | kubectl apply -f -
 apiVersion: certificates.k8s.io/v1
 kind: CertificateSigningRequest
@@ -89,40 +93,41 @@ EOF
 status=$(kubectl get certificatesigningrequest.certificates.k8s.io $user -o json | jq '.status')
 if [ "$status" != '{}' ]
 then
-  echo -ne \n"Запрос на подпись сертификата не выполнен\n"
-  echo "Статус: $status"
+  echo -ne "\n$(gettext 'Certificate signing request failed')\n" >&2
+  echo "$(gettext 'Status'): $status" >&2
   exit 1
 fi
 
 # Подтверждение CSR
-echo -ne "Подтверждение запроса на подпись сертификата (CSR)..."
+echo -ne "\n$(gettext 'Confirming the Certificate Signing Request') (CSR)..." >&2
 kubectl certificate approve $user
 
 statusType=$(kubectl get certificatesigningrequest.certificates.k8s.io $user -o json | jq '.status.conditions[].type')
 if [ "$statusType" != '"Approved"' ]
 then
-  echo "Запрос на подтверждение сертификата не выполнен"
+  echo "$(gettext 'Certificate verification request failed')" >&2
   exit 1
 fi
+echo ""
 
 # Создание сертификата
-echo "Создание сертификата..."
+echo -ne "\n$(gettext 'Creating a certificate')... " >&2
 kubectl get csr $user -o jsonpath='{.status.certificate}'| base64 -d > $user.crt
 if [ ! -s "$user.crt" ]
 then
-  echo "сертификат '$user.crt' не создан"
+  echo "$(gettext 'Certificate') '$user.crt' $(gettext 'not created')" >&2
   exit 1
 fi
-echo "сертификат '$user.crt' создан"
+echo "$(gettext 'Certificate') '$user.crt' $(gettext 'created')" >&2
 
 # Проверка корректности сертификата
-echo -ne "Проверка корректности сертификата..."
+echo -ne "\n$(gettext 'Checking the correctness of the certificate')... " >&2
 TMPFILE=/tmp/$cmdname.$$
 openssl rsa  -noout -modulus -in $user.key | openssl md5 > $TMPFILE
 openssl x509 -noout -modulus -in $user.crt | openssl md5 | cmp $TMPFILE
 if [ $? -gt 0 ]
 then
-  echo -ne "\nЛичный ключ пользователя не соответствуют сгенерированному сертификату\n" >&1
+  echo -ne "\n$(gettext 'The users private key does not match the generated certificate')\n" >&2
   exit 1
 fi
 rm -f $TMPFILE
@@ -131,12 +136,12 @@ echo
 clusterIP=$(getClusterIP)
 URL="/etc/kubernetes/pki/ca.crt"
 
-echo "Введите пароль пользователя $remoteUser в кластере"
+echo "$(gettext 'Enter user password') $remoteUser $(gettext 'in a cluster')" >&2
 if scp $remoteUser@${clusterIP}:$URL ca.crt
 then
   :;
 else
-  echo "Копирование сертификата неудачное" >&2
+  echo "$(gettext 'Copying certificate failed')" >&2
   exit 1
 fi
 
@@ -146,29 +151,30 @@ clusterapi=`kubectl config  view -o jsonpath='{.clusters[0].cluster.server}'`
 kind=$(curl -s --key $user.key --cert $user.crt --cacert ca.crt  $clusterapi/api | jq '.kind')
 if [ "$kind" != '"APIVersions"' ]
 then
-  echo "Запрос на получение API-версии сервера не прошел"
+  echo "$(gettext 'Request to get server API version failed')" >&2
   exit 1
 fi
 
 # Формирование файла конфигурации пользователя
-echo "Формирование файла конфигурации пользователя..."
+echo -ne "$(gettext 'Generating a user configuration file')... " >&2
 kubectl config set-cluster $clustername --certificate-authority=ca.crt --embed-certs=true --server=$clusterapi --kubeconfig=config
 kubectl config set-credentials $user --client-certificate=$user.crt --client-key=$user.key --embed-certs=true --kubeconfig=config
 kubectl config set-context default --cluster=$clustername --user=$user --kubeconfig=config
 kubectl config use-context default --kubeconfig=config
-echo "Файл конфигурации пользователя 'config' создан"
-if [ ! -s "$user.csr" ]
+if [ -s "$user.csr" ]
 then
-  echo "Файл конфигурации 'config' не создан"
+  echo "$(gettext 'User configuration file') 'config' $(gettext 'created')" >&2
+else
+  echo "$(gettext 'User configuration file') 'config' $(gettext 'not created')" >&2
   exit 1
 fi
 
 # Добавление контекста созданного пользователя
-echo -ne "Добавление контекста созданного пользователя..."
+echo -ne "$(gettext 'Adding context to created user')... " >&2
 clustername=$(getClusterName)
 kubectl config set-credentials $user --client-certificate=$user.crt --client-key=$user.key --embed-certs=true
 kubectl config set-context $user --cluster=$clustername --user=$user
-echo "контекст добавлен"
+echo -ne "$(gettext 'context added')... " >&2
 
 
 unsetUserKubeconfigAccess $user
diff --git a/podsec-k8s-rbac/bin/podsec-k8s-rbac-functions b/podsec-k8s-rbac/bin/podsec-k8s-rbac-functions
--- a/podsec-k8s-rbac/bin/podsec-k8s-rbac-functions
+++ b/podsec-k8s-rbac/bin/podsec-k8s-rbac-functions
@@ -5,6 +5,7 @@ setEnv() {
   USERDIR="/home/$user"
   if [ ! -d $USERDIR ]
   then
+    echo "$(gettext'User') $user $(gettext 'missing from the system')" >&2
     echo "Пользователь $user отсутствует в системе" >&2
     exit 1
   fi
@@ -15,14 +16,14 @@ setEnv() {
 setUserKubeconfigAccess() {
   if ! id -nG | grep wheel >/dev/null 2>&1
   then
-    echo "Пользователь не входит в группу wheel" >&2
+    echo "$(gettext 'User') $gettext('not included in the group') wheel" >&2
     exit 1
   fi
   slist=; n=1; while [ $n -le 64 ]; do slist+=" $n"; let n=$n+1; done
   trap "while ! su - -c 'chmod 700 $KUBECONFIGDIR'; do :; done" $slist
   if [ "$(id -u)" -ne 0 ]
   then
-    echo "Введите пароль пользователя root"
+    echo "$(gettext 'Enter password of user') root" >&2
   fi
   while ! su - -c "chmod 770 $KUBECONFIGDIR"; do :; done
 }
@@ -30,13 +31,13 @@ setUserKubeconfigAccess() {
 unsetUserKubeconfigAccess() {
   if ! id -nG | grep wheel >/dev/null 2>&1
   then
-    echo "Пользователь не входит в группу wheel" >&2
+    echo "$(gettext 'User') $gettext('not included in the group') wheel" >&2
     exit 1
   fi
   user=$1
   if [ "$(id -u)" -ne 0 ]
   then
-    echo "Введите пароль пользователя root"
+    echo "$(gettext 'Enter password of user') root" >&2
   fi
   while ! su - -c "chown -R $user:k8s $KUBECONFIGDIR;chmod 700 $KUBECONFIGDIR"; do :; done
 }
@@ -45,7 +46,7 @@ getClusterIP() {
   clusterURL=$(kubectl config  view -o json | jq '.clusters[0].cluster.server')
   if [ -z "$clusterURL" ]
   then
-    echo "Кластер недоступен (файл конфигурации $KUBECONFIGFILE)"
+    echo "$(gettext 'Cluster is unavailable') ($(gettext 'configuration file') $KUBECONFIGFILE)" >&2
     exit 1
   fi
   clusterURL=${clusterURL:1:-1}
@@ -60,7 +61,7 @@ getClusterName() {
   clusterName=$(kubectl config  view -o json | jq '.clusters[0].name')
   if [ -z "$clusterName" ]
   then
-    echo "Кластер недоступен (файл конфигурации $KUBECONFIGFILE)"
+    echo "$(gettext 'Cluster is unavailable') ($(gettext 'configuration file') $KUBECONFIGFILE)" >&2
     exit 1
   fi
   echo $clusterName
diff --git a/podsec-k8s-rbac/bin/podsec-k8s-rbac-get-userroles b/podsec-k8s-rbac/bin/podsec-k8s-rbac-get-userroles
--- a/podsec-k8s-rbac/bin/podsec-k8s-rbac-get-userroles
+++ b/podsec-k8s-rbac/bin/podsec-k8s-rbac-get-userroles
@@ -1,14 +1,19 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec-k8s-rbac'
 
+export PROGRAMM=$0
 if [ $# -lt 1 -a $# -gt 2 ]
 then
-  echo -ne "Неверное число параметров.\nФормат:\n$0 пользователь [showRules]\n"
+  echo  "$(gettext 'Invalid number of parameters'):" >&2
+  echo -ne "$(gettext 'Format':)\n$PROGRAMM $(gettext 'user') [showRules]\n" >&2
   exit 1
 fi
 
 if [ $# -eq 2 -a "$2" != 'showRules' ]
 then
-  echo -ne "Неверный второй параметр.\nФормат:\n$0 пользователь [showRules]\n"
+  echo "$(gettext 'Invalid second parameter')." >&2
+  echo -ne "$(gettext 'Format':)\n$PROGRAMM $(gettext 'user') [showRules]\n" >&2
   exit 1
 fi
 user=$1
@@ -29,7 +34,6 @@ then
     clusterRole+=",\"unbindCmd\":\"$unbindCmd\""
     if [ "$showRules" == 'showRules' ]
     then
-      # echo "Правила роли:"
       rules=$(kubectl get $roleType $roleName -o json | jq '.rules')
       clusterRole+=",\"rules\":$rules"
     fi
@@ -38,32 +42,6 @@ then
   done
 fi
 clusterRoles="\"clusterRoles\":[$clusterRoles]"
-
-# roles=
-# set -- $(kubectl get rolebinding  -o json 2>/dev/null |
-#   jq '.items[] | select((.subjects!=null and .subjects[].name=="'$user'")) | .metadata.name,.roleRef.kind,.roleRef.name')
-# if [ $# -ge 3 ]
-# then
-#   while [ $# -gt 0 ]
-#   do
-#     bindName=${1:1:-1}
-#     roleType=${2:1:-1}
-#     roleName=${3:1:-1}
-#     shift;shift;shift
-#     role="\"bindName\":\"$bindName\",\"roleType\":\"$roleType\",\"roleName\":\"$roleName\""
-#     unbindCmd="podsec-k8s-rbac-unbindrole $user role $roleName $bindName"
-#     role+=",\"unbindCmd\":\"$unbindCmd\""
-#     if [ "$showRules" == 'showRules' ]
-#     then
-#       # echo "Правила роли:"
-#       rules=$(kubectl get $roleType $roleName -o json | jq '.rules')
-#       role+=",\"rules\":$rules"
-#     fi
-#     roles+=${roles:+,}
-#     roles+="{$role}"
-#   done
-# fi
-# allnamespaceRoles="\"allNamespaces\":[$roles]"
 
 namespaceRoles=
 for namespace in $(kubectl get ns -o json | jq '.items[].metadata.name')
diff --git a/podsec-k8s-rbac/bin/podsec-k8s-rbac-unbindrole b/podsec-k8s-rbac/bin/podsec-k8s-rbac-unbindrole
--- a/podsec-k8s-rbac/bin/podsec-k8s-rbac-unbindrole
+++ b/podsec-k8s-rbac/bin/podsec-k8s-rbac-unbindrole
@@ -1,11 +1,13 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec-k8s-rbac'
 
-cmdname=$0
+cmdname=$(basename $0)
 . podsec-k8s-rbac-functions
 
 if [ $# -lt 4 -o $# -gt 5 ]
 then
-  echo -ne "Формат:\n$0 имя_пользователя role|clusterrole|role=clusterrole роль имя_связки_роли [namespace]"
+  echo -ne "$(gettext 'Format'):\n$cmdname $(gettext 'username') role|clusterrole|role=clusterrole $(gettext 'role') $(gettext 'role_bundle_name') [namespace]" >&2
   exit 1
 fi
 
@@ -28,7 +30,7 @@ fi
 
 if [ -z "$isSystem" -a ! -d /home/$user  ]
 then
-  echo "Пользователь $user не существует"
+  echo "$(gettext 'User') $user $(gettext 'does not exist')" >&2
   exit 1
 fi
 
@@ -39,13 +41,14 @@ case $bindedRoleType in
     roleType="role"
     bindedRoleType='clusterrole'
     break;;
-  *) echo "Неверный тип кластерной роли $bindedRoleType";
-    echo -ne "Формат:\n$0 имя_пользователя role|clusterrole|role=clusterrole роль имя_связки_роли [namespace]";
+  *)
+    echo "$(gettext 'Invalid cluster role type') $bindedRoleType" >&2
+  echo -ne "$(gettext 'Format':)\n$cmdname $(gettext 'username') role|clusterrole|role=clusterrole $(gettext 'role') $(gettext 'role_bundle_name') [namespace]" >&2
 esac
 
 if [ -n "$namespace" -a $roleType == 'clusterrole' ]
 then
-  echo "namespace неприменимо к кластерной роли"
+  echo "namespace $namespace $(gettext 'not applicable to cluster role')" >&2
   exit 1
 fi
 
@@ -53,18 +56,18 @@ if ! roleNameDesc=$(kubectl $namespace get ${roleType}binding $bindName -o json 
 then
   if [ $roleType == 'clusterrole' ]
   then
-    roleTxt="Кластерная роль"
+    roleTxt="$(gettext 'Cluster role')"
   else
-    roleTxt="Роль"
+    roleTxt="$(gettext 'Role')"
   fi
-  echo "$roleTxt '$roleName' отсутствует"
+  echo "$roleTxt '$roleName' $(gettext 'absent')" >&2
   exit 1
 fi
 
 deletedSubjects=$(echo $roleNameDesc | jq '[.subjects[] | select(.name!="'$user'")]')
 if [ -z "$deletedSubjects" ]
 then
-  echo "Пользователь $user отсутствует в связке роли $bindName"
+  echo "$(gettext 'User') $user $(gettext 'missing from the role link') $bindName" >&2
   exit 1
 else
   if [ "$deletedSubjects" == '[]' ]
