Added localization of the podsec package.

diff --git a/podsec/bin/podsec-create-policy b/podsec/bin/podsec-create-policy
--- a/podsec/bin/podsec-create-policy
+++ b/podsec/bin/podsec-create-policy
@@ -1,25 +1,28 @@
 #!/bin/sh
 # Скрипт создает
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec'
 
+export cmd=$0
 if [ $# -lt 1 ]
 then
-  echo -ne "Не указан IP-адрес регистратора и сервера подписей\n"
-  echo -ne "Формат:\n\t$0 <ip-адрес_регистратора_и_сервера_подписей>\n"
+  echo $(gettext 'The IP address of the registry and signature server is not specified') >&2
+  echo "$(gettext 'Format'):\n\t$cmd $(gettext '<ip_address_of_registrar_and_signature_server>')\n" >&2
   exit 1
 fi
 
 if [ $# -gt 1 ]
 then
-  echo -ne "Должен быть указан только один IP-адрес регистратора и сервера подписей\n"
-  echo -ne "Формат:\n\t$0 <ip-адрес_регистратора_и_сервера_подписей>\n"
+  echo $(gettext 'Only one IP address of the registry and signature server must be specified.') >&2
+  echo "$(gettext 'Format'):\n\t$cmd $(gettext '<ip_address_of_registrar_and_signature_server>')\n" >&2
   exit 1
 fi
 
-regIP=$1
+export regIP=$1
 
 case $regIP in
   '127.0.0.1')
-    echo "IP-адрес регистратора и сервера подписей не должен быть локальным: $regIP"
+    echo "$(gettext 'The IP address of the registry and signature server must not be local'): $regIP" >&2
     exit 1;;
 esac
 
@@ -28,7 +31,7 @@ set -- $regIP
 IFS=$ifs
 if [ $# -ne 4 ]
 then
-  echo "Некорректный IP-адрес: $regIP"
+  echo "$(gettext 'Invalid IP address'): $regIP" >&2
   exit 2
 fi
 
@@ -37,7 +40,7 @@ do
   if [[ "$a" =~ $re && "$a" -ge 0 && "$a" -lt 256 ]]
   then :;
   else
-  echo "Некорректный IP-адрес: $regIP"
+    echo "$(gettext 'Invalid IP address'): $regIP" >&2
     exit 3
   fi
 done
@@ -63,32 +66,34 @@ fi
 if line=$(grep $regIP /etc/hosts 2>/dev/null)
 then
   set -- $line
-  ip=$1
+  export ip=$1
   shift
   for domain
   do
     if [ "$domain" = 'registry.local' ] || [ "$domain" = 'sigstore.local' ] || [ "$domain" = 'trivy.local'  ]
     then
-      echo "Домены registry.local sigstore.local trivy.local уже привязаны к IP-адресу $ip" >&2
-      echo "Удалите привязку и запустите скрипт заново" >&2
+      echo "$(gettext 'Domains registry.local sigstore.local trivy.local are already bound to IP address') $ip" >&2
+      echo $(gettext 'Remove the binding and run the script again')  >&2
       exit 1
     fi
   done
+else
+  echo "$(gettext 'Adding a binding of domains registry.local sigstore.local trivy.local to IP address') $regIP" >&2
+  echo "$regIP registry.local sigstore.local trivy.local" >> /etc/hosts
 fi
-echo "Добавление привязки доменов registry.local sigstore.local trivy.local к IP-адресу $regIP"
-echo "$regIP registry.local sigstore.local trivy.local" >> /etc/hosts
 
 # Создание группы podman
-echo "Создание группы podman"
+echo $(gettext 'Creating podman group')  >&2
 groupadd -r podman >/dev/null 2>&1
-echo "Инициализация каталога /var/sigstore/ и подкаталогов хранения открытых ключей и подписей образов"
-# Создание каталога и подкаталогов  /var/sigstore/ если IP-адрес узла совпадает с IP-адресом сервера подписей storage.local
-echo "Создание каталога и подкаталогов  /var/sigstore/"
+echo "$(gettext 'Initializing the') /var/sigstore/ $(gettext 'directory and subdirectories for storing public keys and image signatures')" >&2
+
+# Создание каталога и подкаталогов /var/sigstore/ если IP-адрес узла совпадает с IP-адресом сервера подписей storage.local
+echo "$(gettext 'Creating the directory and subdirectories') /var/sigstore/" >&2
 mkdir -p -m 0775 /var/sigstore/keys/
 if [ -n "$localIP" ]
 then
   #IP-адрес узла совпадает с IP-адресом сервера подписей storage.local
-  echo "Создание группы podman_dev"
+  echo $(gettext 'Creating the podman_dev group') >&2
   groupadd -r podman_dev >/dev/null 2>&1
   # Создать каталог sogstore с подкаталогами
   chown root:podman_dev /var/sigstore/keys/
@@ -110,7 +115,7 @@ yesterday=$(date '+%Y-%m-%d_%H:%M:%S' -d "yesterday")
 now=$(date '+%Y-%m-%d_%H:%M:%S')
 
 # Создание с сохранением предыдущего файла политик /etc/containers/policy.json
-echo "Создание с сохранением предыдущего файла политик /etc/containers/policy.json"
+echo "$(gettext 'Creating with preservation of the previous policy file') /etc/containers/policy.json" >&2
 if [ ! -L $policyFile ]
 then :;
   mv $policyFile "policy_${yesterday}"
@@ -134,7 +139,7 @@ fi
 ln -sf $linkedPolicyFile $policyFile
 
 # Создание с сохранением предыдущего файла `/etc/containers/registries.d/default.yaml` описания доступа к открытым ключам подписантов
-echo "Создание с сохранением предыдущего файл /etc/containers/registries.d/default.yaml описания доступа к открытым ключам подписантов"
+echo "$(gettext 'Creating with preservation of the previous file') /etc/containers/registries.d/default.yaml $(gettext 'description of access to public keys of signatories')" >&2
 cd /etc/containers/registries.d
 defaultYaml='default.yaml'
 if [ ! -L $defaultYaml ]
@@ -150,7 +155,7 @@ ln -sf $linkedDefaultYaml $defaultYaml
 
 cd /etc/containers
 # Добавление insecure-доступа к регистратору registry.local в файле /etc/containers/registries.conf
-echo "Добавление insecure-доступа к регистратору registry.local в файле /etc/containers/registries.conf"
+echo "$(gettext 'Adding insecure access to the registry.local registry in the') /etc/containers/registries.conf file" >&2
 registriesConf="registries.conf"
 if [ ! -L $registriesConf ]
 then :;
diff --git a/podsec/bin/podsec-create-services b/podsec/bin/podsec-create-services
--- a/podsec/bin/podsec-create-services
+++ b/podsec/bin/podsec-create-services
@@ -1,4 +1,6 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec'
 
 . podsec-functions
 
@@ -6,7 +8,7 @@ mes=$(isSigstoreServer)
 if [ -n "$mes" ]
 then
   echo -ne $mes >&2
-  echo "Запуск сервисов невозможен." >&2
+  echo "$(gettext 'Services cannot be started')."  >&2
   exit 1
 fi
 
@@ -27,8 +29,8 @@ podman volume create registry
 sed -i -e 's|rootdirectory:.*|rootdirectory: /var/lib/containers/storage/volumes/registry/_data/|' -e 's/addr:.*/addr: :80/' /etc/docker-registry/config.yml
 if systemctl | grep httpd2 | grep running >/dev/null 2>&1
 then
-  echo "Сервис httpd2 запущен и конфликтует с docker-registry"
-  echo "Сервис httpd2 остановлен"
+  echo $(gettext 'Service httpd2 is running and conflicts with docker-registry')  >&2
+  echo $(gettext 'Service httpd2 stopped')  >&2
   systemctl disable --now httpd2
 fi
 systemctl enable --now docker-registry
diff --git a/podsec/bin/podsec-load-sign-oci b/podsec/bin/podsec-load-sign-oci
--- a/podsec/bin/podsec-load-sign-oci
+++ b/podsec/bin/podsec-load-sign-oci
@@ -1,4 +1,8 @@
 #!/bin/sh
+export cmd=$0
+
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec'
 
 source podsec-functions
 source podsec-get-platform
@@ -9,24 +13,24 @@ mes=$(isSigstoreServer)
 if [ -n "$mes" ]
 then
   echo $mes >&2
-  echo "Загрузка образов невозможна"
+  echo $(gettext 'Unable to load images')  >&2
   exit 1
 fi
 
 if ! id | grep -q podman_dev
 then
-  echo "Скрипт вызывается пользователем не входящим в группу podman_dev" >&2
+  echo $(gettext 'The script is called by a user not included in the podman_dev group') >&2
   exit 1
 fi
 
 if [ $# -ne 4 -a $# -ne 3 ]
 then
-  echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer [registry/path]')\n" >&2
   exit 1
 fi
 
-archive=$1
-arch=$2
+export archive=$1
+export arch=$2
 # regName=$(basename $3)
 signBy="${3}"
 if [ $# -eq 3 ]
@@ -37,8 +41,8 @@ else
   dir=$(dirname $4)
   if [ $dir == '.' ]
   then
-    echo "Отсутствует тропа после имени регистратора"
-    echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+    echo $(gettext 'Missing path after registry name') | envsubst >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer registry/path')\n" >&2
     exit 1
   fi
   base="$(basename $4)"
@@ -49,25 +53,25 @@ baselen=${#base}
 
 if [ ! -f $archive ]
 then
-  echo "Архив $archive отсутствует"
-  echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+  echo "$(gettext 'Archive') $archive $(gettext 'is missing')" >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer registry/path')\n" >&2
   exit 1
 fi
 
 case $arch in
 amd64 | arm64 | arm | ppc64le | 386) :;;
 *)
-  echo "Неизвестная архитектура $arch" >&2
-  echo "Допустимые: amd64, arm64, arm, ppc64le, 386" >&2
-  echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+  echo "$(gettext 'Unknown architecture') $arch" >&2
+  echo $(gettext 'Allowed: amd64, arm64, arm, ppc64le, 386') >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer registry/path')\n" >&2
   exit 3
   ;;
 esac
 
 if [ -z "$regName" ]
 then
-  echo "Не указано имя регистратора" >&2
-  echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+  echo $(gettext 'Registry name not specified')  >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer registry/path')\n" >&2
   exit 4
 fi
 
@@ -78,8 +82,8 @@ set -- $1
 IFS=$ifs
 if [ $# -eq 1 ]
 then
-  echo "Имя регистратора должно содержать точку (.) в имени" >&2
-  echo -ne "Формат:\n\t$0 имя_архивного_файла архитектура EMail_подписанта [регистратор/тропа]\n"  >&2
+  echo $(gettext 'The registry name must contain a period (.) in the name')  >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_file_name architecture EMail_signer registry/path')\n" >&2
   exit 5
 fi
 
@@ -90,21 +94,21 @@ if xz -d < $archive | tar xvCf $TMPDIR -
 then
   :;
 else
-  echo "Неуспешное разворачивание архива" >&2
+  echo $(gettext 'Unsuccessful archive unfolding')  >&2
   exit 6
 fi
 
 archDir="$TMPDIR/$arch"
 if [ ! -d $archDir ]
 then
-  echo "Неверный формат архива. Каталог архитектуры $arch отсутствует" >&2
+  echo "$(gettext 'Invalid archive format. Archive directory') $arch $(gettext 'is missing')" >&2
   exit 7
 fi
 
 archIndexFile="$archDir/index.json"
 if [ ! -f "$archIndexFile" ]
 then
-  echo "Неверный формат архива. Индексный файл архива $arch/index.json отсутствует" >&2
+  echo "$(gettext 'Invalid archive format. Architecture directory') $arch/index.json $(gettext 'is missing')" >&2
   exit 8
 fi
 
@@ -114,12 +118,11 @@ ifs=$IFS
 IFS=/
 set -- $image
 IFS=$ifs
-platform=$1
-
+export platform=$1
 if [ "$platform" != "$U7S_PLATFORM" ]
 then
-  echo "Текущая платформа $U7S_PLATFORM не совпадает c устанавливаемой $platform"
-  echo "Продолжать (y/N)?"
+  echo "$(gettext 'Current platform') $U7S_PLATFORM $(gettext 'does not match installed') $platform" >&2
+  echo $(gettext 'Continue (y/N)?') >&2
   read answer
   if [ "$answer" != "y" ]
   then
@@ -140,7 +143,7 @@ ImageList=""
 for image in $imagesList
 do
   image=${image:1:-1}
-  echo "Разворачивание образа $image в локальную систему"
+  echo "$(gettext 'Deploying the image') $image $(gettext 'to the local system')" >&2
   if [ "${image:0:$baselen}" == "$base" ]
   then
     image=${image:$baselen}
@@ -163,7 +166,7 @@ done
 
 for Image in $ImageList
 do
-  echo "Подпись и передача образа $Image в регистратор"
+  echo "$(gettext 'Signing and transferring the') $Image $(gettext 'to the registry')" >&2
   podman push --tls-verify=false --sign-by="$signBy" $Image
 done
 
