Added localization of the podsec package.

diff --git a/podsec/bin/podsec-create-imagemakeruser b/podsec/bin/podsec-create-imagemakeruser
--- a/podsec/bin/podsec-create-imagemakeruser
+++ b/podsec/bin/podsec-create-imagemakeruser
@@ -1,4 +1,6 @@
 #!/bin/sh
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec'
 
 # Создание пользователя $user
 createImageMaker() {
@@ -6,10 +8,11 @@ createImageMaker() {
   IFS=@
   set -- $1
   IFS=$ifs
-  user=$1 regPath=$2
-#   linkedPolicyFile=$linkedPolicyFile
+  export user=$1
+  regPath=$2
   adduser $user -g podman -G podman_dev
-  echo "Введите пароль пользователя $user - разработчика  образов контейнеров"
+
+  echo "$(gettext 'Enter the password for user') $user - $(gettext 'the container image developer')" >&2
   passwd $user
 
   cd /home/$user
@@ -38,7 +41,8 @@ createImageMaker() {
   set -- $(su - -c 'gpg2 --list-keys'  $user)
   if [ $# -lt 1 ]
   then
-    echo "Не найден открытый ключ"
+    echo "$(gettext 'Public key not found')" >&2
+#     echo "Не найден открытый ключ"
     exit 1
   fi
   # Вытащить uid из ключа
@@ -77,7 +81,7 @@ testRepoPath() {
     user=$1 repoPath=$2
     if [ $# -ne 2 -o -z "$user" -o -z "$repoPath" ]
     then
-      echo -ne "Неверный формат описания тропы репозитория для пользователя $*;Формат: <пользователь>@<тропа_репозитория>\n"
+      echo "$(gettext 'Invalid repository path description format for user') $user; $(gettext 'Format'): <user>@<repository_path>\n" >&2
       exit 1
     fi
     repoPaths+="\n$repoPath"
@@ -95,7 +99,7 @@ testRepoPath() {
         then
           let n=$n+1
         else
-          echo "Две совпадающие тропы репозитория $repoPath" >&2
+          echo "$(gettext 'Two matching repository paths') $repoPath" >&2
           exit 2
         fi
       fi
@@ -108,19 +112,19 @@ testRepoPath() {
 
 if [ $(id -u) -ne 0 ]
 then
-  echo "Скрипт должен запускаться пользователем с правами root"
+  echo "$(gettext 'The script must be run by a user with root rights.')" >&2
   exit 1
 fi
 
 . podsec-functions
 
 # Проверка. Является ли текущий сервер сервером, поддерживающий регистратор (registry.local) и сервер подписи образов (sigstore.local)
-echo "Проверка. Является ли текущий сервер сервером, поддерживающий регистратор (registry.local) и сервер подписи образов (sigstore.local)"
+echo "$(gettext 'Check if the current server is a server that supports the registry (registry.local) and the image signing server (sigstore.local)')" >&2
 mes=$(isSigstoreServer)
 if [ -n "$mes" ]
 then
   echo $mes >&2
-  echo "Создание пользователей класса 'разработчик образов контейнеров' невозможно" >&2
+  echo "$(gettext 'It is not possible to create users of the container image developer class')" >&2
   exit 1
 fi
 
@@ -128,8 +132,8 @@ users=$(testRepoPath $*)
 
 if [ ! -d "/var/sigstore/" ]
 then
-  echo "Не создан каталог /var/sigstore/ сервера подписей" >&2
-  echo "Вызовите скрипт podsec-create-policy для его инициализации" >&2
+  echo "$(gettext 'Signature server directory /var/sigstore/ not created')" >&2
+  echo "$(gettext 'Call the podsec-create-policy script to initialize it')" >&2
   exit 1
 fi
 
diff --git a/podsec/bin/podsec-save-oci b/podsec/bin/podsec-save-oci
--- a/podsec/bin/podsec-save-oci
+++ b/podsec/bin/podsec-save-oci
@@ -12,17 +12,21 @@
 # При необходимости нужно будет произвести перезагрузку образов для рабочей архитектуры процессора
 #set -x
 
+export TEXTDOMAINDIR='/usr/share/locale'
+export TEXTDOMAIN='podsec'
+export cmd=$1
+
 if [ $# -lt 1 ]
 then
-  echo "Не указан каталог архивирования образов"
-  echo -ne "Формат:\n\t$0  <каталог_архивирования_образов> <архитектура>,<архитектура>,...|all <транспорт> <образ> ..."
+  echo "$(gettext 'Image archiving directory not specified')\n" >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_deployment_directory [architecture ...] [transport] [image] ...')\n" >&2
   exit 1
 fi
 
 if [ $# -eq 1 ]
 then
-  echo "Не указан список образов"
-  echo -ne "Формат:\n\t$0  <каталог_архивирования_образов> <архитектура>,<архитектура>,...|all <транспорт>  <образ> ..."
+  echo "$(gettext 'No list of images specified')" >&2
+  echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_deployment_directory [architecture ...] [transport] [image] ...')\n" >&2
   exit 1
 fi
 
@@ -40,7 +44,7 @@ images=$*
 
 if [ -d $ociDir ]
 then
-  echo "OCI-каталог уже существует"
+  echo $(gettext 'OCI catalog already exists') >&2
   exit 1
 fi
 
@@ -54,14 +58,15 @@ case $archs in
     IFS=$ifs
     archs=$*
     IFS=$ifs
+    export arch
     for arch in $archs
     do
       case $1 in
         amd64 | arm64 | arm | ppc64le | 386) :;;
         *)
-          echo "Неизвестная архитектура $arch";
-          echo "Допустимые: amd64, arm64, arm, ppc64le, 386"
-          echo -ne "Формат:\n\t$0 каталог_разворачивания_архивов [архитектура ...] [транспорт]  [образ] ...\n"
+          echo "$(gettext 'Unknown architecture') $arch" >&2
+          echo "$(gettext 'Allowed: amd64, arm64, arm, ppc64le, 386')" >&2
+          echo -ne "$(gettext 'Format'):\n\t$cmd $(gettext 'archive_deployment_directory [architecture ...] [transport] [image] ...')\n" >&2
           exit 2
       esac
     done
@@ -70,10 +75,10 @@ esac
 mkdir $ociDir
 if [ -n "$PODSECSAVE_USEEXISTINGIMAGES" ]
 then
-  storage="/var/lib/u7s-admin/.local/share/usernetes/containers/storage/"
+  export storage="/var/lib/u7s-admin/.local/share/usernetes/containers/storage/"
   if [ ! -d $storage ]
   then
-    echo "Каталог $storage отсутствует. Копирование существующих образов  пользователя u7s-admin невозможно."
+    echo "$(gettext 'Directory') $storage $(gettext 'is missing. Copying existing images of user u7s-admin is not possible.')" >&2
   fi
 fi
 
@@ -85,9 +90,10 @@ do
   then
     mkdir $ociArchDir
   fi
+  export image
   for image in $images
   do
-    echo -ne "\n------------------------\nАрхивация образа $image\n"
+    echo "\n------------------------\n$(gettext 'Archiving the image') $image\n" >&2
     Image="$regName/$image"
     podman image rm $image >/dev/null 2>&1
 #     if [ -n "$PODSECSAVE_USEEXISTINGIMAGES" ]
@@ -108,7 +114,7 @@ do
       containers-storage:$Image\
       oci:$ociArchDir:$image  2>/dev/null
   done
-  echo -ne "\n------------------------\nАрхивания и сжатие образов\n"
+  echo "\n------------------------\n$(gettext 'Archiving and compressing images\n')" >&2
   tar cvCf $ociDir -  $arch | xz -9v > $ociArchDir.tar.xz
   rm -rf $ociArchDir
 done
