Оптимизация кода systemctl@u7s

diff --git a/usernetes/bin/systemctl b/usernetes/bin/systemctl
--- a/usernetes/bin/systemctl
+++ b/usernetes/bin/systemctl
@@ -3,45 +3,45 @@
 source podsec-u7s-functions
 set -x
 
- logger -- "`(echo -ne "$0: TIME=$(date  +%H:%M:%S.%N) UID=$UID PID=$(cat $XDG_RUNTIME_DIR/usernetes/rootlesskit/child_pid) PARS=$*")`"
- echo -ne "$0: TIME=$(date  +%H:%M:%S.%N) UID=$UID PID=$(cat $XDG_RUNTIME_DIR/usernetes/rootlesskit/child_pid) PARS=$*\n" >&2
+# logger -- "`(echo -ne "$0: TIME=$(date  +%H:%M:%S.%N) UID=$UID PID=$(cat $XDG_RUNTIME_DIR/usernetes/rootlesskit/child_pid) PARS=$*")`"
+# echo -ne "$0: TIME=$(date  +%H:%M:%S.%N) UID=$UID PID=$(cat $XDG_RUNTIME_DIR/usernetes/rootlesskit/child_pid) PARS=$*\n" >&2
 
-(
-exec 2>>/tmp/systemctl.log
-echo -ne "\n\n___________________________\n"
-set -x
+# exec 2>>/tmp/systemctl.log
+# echo -ne "\n\n___________________________\n"
 
-userMode=
-if [ $1 == '--user' ]
-then
-  userMode=1
-  shift
-fi
 
-cmd=$1
-target=$2
-if [ "$target" != 'kubelet' -o $# -lt 2 ]
-then
-  /sbin/systemctl --user -M u7s-admin@ -T $@
-  exit 0
-fi
+/sbin/systemctl --user -M u7s-admin@ -T $@
 
-shift; shift
-retry=60
+# userMode=
+# if [ $1 == '--user' ]
+# then
+#   userMode=1
+#   shift
+# fi
+#
+# cmd=$1
+# target=$2
+# if [ "$target" != 'kubelet' -o $# -lt 2 ]
+# then
+#   /sbin/systemctl --user -M u7s-admin@ -T $@
+#   exit 0
+# fi
+#
+# shift; shift
+# retry=60
+#
+# case $cmd in
+#   start | restart )
+#     echo "$cmd $target"
+#     echo "SYSTEMCTL: $cmd $target TIME=";date  +%H:%M:%S.%N >&2
+# #     logger "$(echo "SYSTEMCTL: START kubelet TIME=";date  +%H:%M:%S.%N)"
+#     /sbin/systemctl --user -M u7s-admin@ -T $cmd kubelet $@
+# #     /sbin/systemctl --user -M u7s-admin@ -T $cmd flanneld $@
+#     exit 0
+#   ;;
+#   *)
+#     /sbin/systemctl --user -M u7s-admin@ -T $cmd kubelet $@
+#     ;;
+# esac
 
-case $cmd in
-  start | restart )
-    echo "$cmd $target"
-    echo "SYSTEMCTL: $cmd $target TIME=";date  +%H:%M:%S.%N >&2
-    logger "$(echo "SYSTEMCTL: START kubelet TIME=";date  +%H:%M:%S.%N)"
-
-    /sbin/systemctl --user -M u7s-admin@ -T $cmd kubelet $@
-#     /sbin/systemctl --user -M u7s-admin@ -T $cmd flanneld $@
-    exit 0
-  ;;
-  *)
-    /sbin/systemctl --user -M u7s-admin@ -T $cmd kubelet $@
-    ;;
-esac
-)&
 
